### ISSUE TITLE
AADM Authoring: KB-Reasoning enhancements for context-aware content-assistance

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/ide#3]
AADM textual editor offers users with context-aware content-assistance that suggests improvements in AADM based on the information that the editor can look up in the model itself, but also on the knowledge learnt (by reasoning) from the KB, through the KB-Reasoner. Existing AADM Editor-KB Reasoner assistance needs to enhanced in different ways:
- Suggest the creation of needed node templates required to satisfy requirements in other existing AADM nodes
_Example: if AADM contains a DockerizedComponent, the IDE-KB interactions should suggest the creation of a DockerHost where to host it, based on the host requirement._ Note: **Could be implemented right now in the IDE!**
- Suggest to override properties/attributes that are mandatory in a node template. This is required for mandatory properties without a default value. KB Reasoner will provide the mandatory parameter. IDE will support this feature - Not in M18
- Rank properties/attributes placing first those that are more overridden by the other AOEs - Not in M18
- Suggest popular values for properties/attributes based on what other AOEs have overridden in other AADMs - Not in M18
- Check property/value validity based on acceptable value type and range - Not in M18
- **Suggest requirements that need to be satisfied. Suggest existing nodes (in AADM or KB) that may satisfy these requirements**: [Analysis](https://github.com/SODALITE-EU/ide/issues/3#issuecomment-646001865) - **Done**
- Suggest possible compatible types for a node template. _This feature is available, but it returns all possible types filter out incompatible existing types, returning only the suitable ones_: 
[Analysis](https://github.com/SODALITE-EU/ide/issues/3#issuecomment-646020451) @jesus-gorronogoitia (if you agree, I can make it bold) - Not in M18
- Filter types to include only those that are related to the types of the nodes currently defined within the AADM. Related with about bullet point
- Rank types by popularity. - Not in M18
- Suggest capabilities that could be overridden by the node template, from those defined in its corresponding type - Not in M18
- Suggest optimization features based on the compute capabilities of the host where the software component is executed - Addressed in [KB semantic reasoner issue 2](https://github.com/SODALITE-EU/semantic-reasoner/issues/2)
- In functions such as getAttribute, getProperty, suggest the compatible attributes, properties available in defined types. Addressed in [KB semantic reasoner issue 5](https://github.com/SODALITE-EU/semantic-reasoner/issues/5)

AADM models should be acceptable if some requirements are not fulfilled by the user
during deployment, optimal resources that match unsatisfied requirements could be assign to them

@gmeditsk @zoevas Could we discuss these and other examples of interaction between the AADM editor and the KB to implement this support?

**Comment by zoevas** [comment]
Hello @jesus-gorronogoitia ,


Regarding the following point:

> Suggest requirements that need to be satisfied. Suggest existing nodes (in AADM or KB) that may satisfy these requirements


As we discussed in the meeting, that the IDE user might send an aadm without a requirement, and the reasoner should find potential matching nodes to the requirement.
Since we have the snow example, I ll describe an example on it.

```
snow-vm:
		type: sodalite.nodes.OpenStack.VM
		...
		#The IDE user will not send this requirement for saving to the KB
		requirements:
			...
			protected_by:
				node: security-rules-snow
```

				

**RESOURCE MODEL:**

```
sodalite.nodes.OpenStack.VM:
		derived_from:tosca.nodes.Compute
		
		
		requirements:
			protected_by:
				capability: tosca.capabilities.Node 
				node: sodalite.nodes.OpenStack.SecurityRules
				relationship: tosca.relationships.DependsOn
```
				

So the reasoner should find if there are available node templates that are of type sodalite.nodes.OpenStack.SecurityRules.
**Those node templates should also have tosca.capabilities.Node  capability?**  In the snow example, security-rules-snow has not any capability.

**Scenario 1:**
_**One matching node** - model is saved_
1) User sends the aadm for snow-vm without the requirements   through /saveAADM

```
requirements
	protected_by:
				node: security-rules-snow
```
2) The reasoner finds that security-rules-snow could satisfy this requirement, and the reasoner associates this node with the requirement of
	snow-vm and saves it.
	
	Should the reasoner return any information to the IDE  about this requirement added with the available node so as the IDE user to have this information available for the seralization to json or for
any other reason?

**Scenario 2:**
**_Two matching nodes - model is not saved - error returned including the matching nodes_**
1) User sends the aadm for snow-vm without the requirements   through /saveAADM

```
requirements
	protected_by:
				node: XXXXX	
```		
2) The reasoner finds that two nodes that could satisfy this requirement.
The model is not saved to the KB, and an error is thrown since the model has not been saved.
The error indicates that a requirement is not fullfilled, and includes the nodes that could satisfy the requirement.
3) The IDE user selects a node and adds it to the requirement and sends /saveAADM.
4) The model is saved successfully to the KB.

**Scenario 3:**
**_No matching node - model is not saved, error returned_**
1) User sends the aadm for snow-vm without the requirements   through /saveAADM

```
requirements
	protected_by:
				node: XXXXX
```
				
2) The reasoner cannot find any node satisfying the protected_by requirement, an error is returned to the IDE indicating
that the requirement has not be fullfilled, and there is not a node available for satisfying it.


Any suggestion or objection?


Thanks in advance,
Zoe

**Comment by zoevas** [comment]
Hello @kartshy,

Just for confirmation, I understood from the last ontology meeting, that for now, the reasoner will
just check which are the applicable optimizations and return the optimizations to the IDE.
Would you agree?

For finding which are the applicable optimizations, reasoner checks which are the capabilities of a node template and few parameters from the optimization json such as app_type, cpu_type,  ai_framework. Please, inform me in case any other parameter should be taken into account.
Regarding the app_type, cpu_type and ai_framework, I understand that the values of those variables cannot be inferred from the rest of the aadm, so the reasoner should retrieve that information from the optimisation json string for finding if the application is hpc or ai, and which framework is selected for ai.

Please, correct me if I am wrong in any point.

_**So as to start the implementation as soon as possible, could you provide an **end-to-end** example, by providing an aadm with node templates having capabilities, an optimization json,  the constraints that the reasoner should check for return optimizations, and the expected optimizations that  should be returned by the reasoner.**_

Any other that we should take in mind regarding the reasoner? Should the reasoner send anything to optimizer? Or for now, just the IDE will send the serialized optimization json to the optimizer, and just the reasoner will assist the IDE by sending the applicable optimizations to IDE.


Thank you so much in advance,
Zoe

**Comment by zoevas** [comment]
> Suggest requirements that need to be satisfied. Suggest existing nodes (in AADM or KB) that may satisfy these requirements


### CASE requirement mandatory omitted by the IDE user
The protected_by requirement is omitted by the user.
e.g.
```
 requirements
	protected_by:
				node: security-rules-snow
```
saveAADM (The request IDE call for saving an AADM) will have one parameter e.g. _complete_ with values True/False.

- When value is true, the reasoner resolves missing requirements and saves the model.
- When value is false, the reasoner returns error along with a recommendation with matching nodes.

		
Initially, the user saves the aadm model with _complete=**false**_.
The model is not saved so as the KB not to have an inconsistent aadm,  and an error is returned with the recommendation (matching nodes).
Then, the user can send, before the deployment, the same model for saving with _complete=**true**_, and the reasoner will automatically resolve this missing requirement if possible, otherwise returns error with recommendation:
1) One matching node - model is saved
The reasoner addsthe missing requirement to the model.
The model is saved. The response should indicate if the model has been modified, and
what has been modified so as to be highlighted to the IDE what has been modified.
2) Two matching nodes - model is not saved - error returned including recommendation with  the matching nodes
3) No matching node - model is not saved, error returned that no node match found satisfying
the requirement

@dradX we discussed it in the ontology meeting. I tag you just for visibility, in case you have any objection or suggestion.

**Comment by zoevas** [comment]
> Suggest possible compatible types for a node template

	Suggest node types that are requirements of the types of  existing node templates in the current aadm.
	Example:
		 If AADM contains a DockerizedComponent, the IDE-KB interactions should suggest the creation of a DockerHost. 
Since the AADM has not been saved yet, the IDE can send as a parameter (could be empty or optional) to the request returning the node types, a list with the current node types in the aadm. Also, there will be a parameter which will be true or false (NOT SURE FOR THIS) indicating if the most related nodes should be returned at the top of the list.
	If the parameter is **true**, the most related nodes are ranked at the top of the list, and the rest of node types are also returned below the aforementioned list with the related nodes.
      If the parameter is **false**, all the node types are returned without any ranking related to relevance with existing node templates.

**Comment by zoevas** [comment]
**Regarding the requirements:**
In [dsl example](https://github.com/SODALITE-EU/ide/blob/master/dsl/org.sodalite.dsl.examples/snow/snow.aadm), I see about _protected_by_, node is defined:
```
protected_by:
				node: security-rules-snow
```
However, in exchange format, we have just protected_by [here](https://github.com/SODALITE-EU/semantic-models/blob/master/ontology%20definitions/examples/exchange/snow_latest.ttl):
```
:Requirement_1
  rdf:type exchange:Requirement ;
  exchange:name "protected_by" ;
  exchange:value "security-rules-snow" ;
.
```
Is this correct? I was expecting to be:
```
:Requirement_1
  rdf:type exchange:Requirement ;
  exchange:name "protected_by" ;
  exchange:hasParameter :Parameter_1 ;
.
:Parameter_1
 rdf:type exchange:Parameter ;
  exchange:name "node" ;
  exchange:value "security-rules-snow" ;
.
```

**Comment by jesus-gorronogoitia** [comment]
TODO: Implement this feature:
Suggest the creation of needed node templates required to satisfy requirements in other existing AADM nodes
Example: if AADM contains a DockerizedComponent, the IDE-KB interactions should suggest the creation of a DockerHost where to host it, based on the host requirement.

Hint: Use [XText custom validation](https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation) to verify if some requirements cannot be satisfied with existing instances.

**Comment by jesus-gorronogoitia** [comment]
TODO: discuss with @zoevas how to retrieve from the KB all the types that could satisfy a given node template requirement. Current implementation is wrong and only works when there are already types satisfying the requirement, but not when there are not

**Comment by jesus-gorronogoitia** [comment]
Content-assistance for AADM complete as what regards needs for existing UC models.
In case of get-property function, support for SELF entity is implemented. Support for other cases and referenced entities is pending. Similar content-assistance for get_attribute function is pending
